project:
  type: website
  output-dir: docs
website:
  title: "Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - text: Resume
        href: https://nathan-swenson.github.io/Portfolio/posts/Resume/Resume/Resume.pdf
      - text: Cover Letter
        href: https://nathan-swenson.github.io/Portfolio/posts/Cover%20Letter/index.pdf
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
editor: visual

